@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiYW5naWVAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY0MDI1NDUzLCJleHAiOjE3NjQxMTE4NTN9.zy7y5Dp643lFQbae1pRL4UvJhI_6mtxaAa_k_cwyXzE
### Crear usuario cliente
POST {{baseUrl}}/auth/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Yuleibis",
    "apellido": "Armenta",
    "email": "angiecabal35@gmail.com",
    "telefono": "30463634447",
    "password": "1111111"

}

### Crear usuario ADMIN
POST {{baseUrl}}/users 
Content-Type: application/json
Authorization: Bearer {{token}} 

{
    "nombre": "Nuevo",
    "apellido": "Administrador",
    "email": "nuevo.admin@empresa.com",
    "telefono": "30463634447",
    "password": "1111111",
    "roleId": 1
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "angie@gmail.com",
    "password": "1111111"
}

### Listar todos los usuarios (solo admin)
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Obtener un usuario por ID
GET {{baseUrl}}/users/1
Authorization: Bearer {{token}}

### Actualizar un usuario
PATCH {{baseUrl}}/users/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "telefono": "310998790",
    "password": "12345678910"
}

### Eliminar un usuario (solo admin)
DELETE {{baseUrl}}/users/2
Authorization: Bearer {{token}}
